ARG FROM_IMAGE_NAME
FROM ${FROM_IMAGE_NAME}
LABEL maintainer="Aleksei Burov <burov_alexey@mail.ru>"

WORKDIR /opt/kbe/src/
RUN make
# TODO: проверить, что будет работать после удаления
# RUN rm -r /opt/kbe/src/
