FROM centos:centos7
LABEL maintainer="Aleksei Burov <burov_alexey@mail.ru>"

RUN yum groupinstall 'Development Tools' -y \
    && yum install mariadb-devel -y \
    && yum install python3 -y \
    && yum install net-tools -y
