version: '3'

services:

  kbe-mariadb:
    image: ${KBE_DB_IMAGE_NAME}
    container_name: ${KBE_DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - kbe-mariadb-volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - kbe-net
    command: --log_warnings=9

  kbe-assets:
    image: ${KBE_ASSETS_IMAGE_NAME}
    container_name: ${KBE_ASSETS_CONTAINER_NAME}
    restart: always
    ports:
      # LoginApp
      - 20013:20013
      # BaseApp
      - 20015-20019:20015-20019
      - 20005-20009:20005-20009/udp
      # telnet
      - 40000-40009:40000-40009
      - 50000-50009:50000-50009
      # Bots
      # telnet
      - 51000:51000
    volumes:
      - kbe-log-kbeengine:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    entrypoint: ["./wait-for-it.sh", "kbe-mariadb:3306", "--", "/bin/bash", "docker-entrypoint.sh"]

volumes:
  kbe-mariadb-volume:
  kbe-log-kbeengine:

networks:
  kbe-net:
