version: '3'

services:

  kbe-mariadb:
    image: ${KBE_DB_IMAGE_TAGGED_NAME}
    container_name: ${KBE_DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - kbe-mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - kbe-net
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 2
    command: --log_warnings=9

  kbe-assets:
    image: ${KBE_ASSETS_IMAGE_NAME}
    container_name: ${KBE_ASSETS_CONTAINER_NAME}
    restart: always
    depends_on:
      - machine: { condition: service_healthy }
    ports:
      # LoginApp
      - 20013:20013
      # BaseApp
      - 20015-20019:20015-20019
      - 20005-20009:20005-20009/udp
      # Baseapp telnet
      - 40000-40009:40000-40009
      # Cellapp telnet
      - 50000-50009:50000-50009
      # Bots telnet
      - 51000:51000
      # Debug ports:
      # Machine
      - 20099:20099
      # Interfaces telnet
      - 33000:33000
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    workdir: /opt/kbengine/assets
    entrypoint: [".shedu/scripts/deploy/docker-entrypoint.sh"]

volumes:
  kbe-mariadb-data:
  kbe-log-data:

networks:
  kbe-net:
