version: '3'

services:

  kbe-mariadb:
    image: ${KBE_DB_IMAGE_TAGGED_NAME}
    container_name: ${KBE_DB_CONTAINER_NAME}
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - kbe-mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - kbe-net
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --host=kbe-mariadb -P 3306 --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --silent --execute "SELECT 1;"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 0
    command: --log_warnings=9

  kbe-machine:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      - proxy_dep
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-machine
    restart: always
    environment:
      KBE_COMPONENT_NAME: machine
      KBE_COMPONENT_ID: 2129652375332859700
    ports:
      - 20099:20099
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
      - ./data/log4j/log4cxx_properties:/opt/kbengine/assets/res/server/log4cxx_properties:ro
    networks:
      - kbe-net
    entrypoint: bash /opt/kbengine/assets/.shedu/scripts/deploy/start_component.sh

volumes:
  kbe-mariadb-data:
  kbe-log-data:
    external:
      name: ${ELK_COMPOSE_PROJECT_NAME}_kbe-log-data

networks:
  kbe-net:
