version: '3'

services:

  kbe-mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - kbe-mariadb-volume:/var/lib/mysql
    container_name: "kbe-mariadb"
    networks:
      - kbe-net

  kbe-assets:
    image: ${IMAGE}
    restart: always
    container_name: kbe-assets
    ports:
      # LoginApp
      - 20013:20013
      # BaseApp
      - 20015-20019:20015-20019
      - 20005-20009:20005-20009/udp
      # telnet
      - 40000-40009:40000-40009
      # Bots
      # telnet
      - 51000:51000
    entrypoint: ["./wait-for-it.sh", "kbe-mariadb:3306", "--", "/bin/bash", "docker-entrypoint.sh"]
    networks:
      - kbe-net

volumes:
  kbe-mariadb-volume:

networks:
  kbe-net:
  
