version: '3'

services:

  machine:
    image: ${KBE_ASSETS_IMAGE_NAME}
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-machine
    restart: "no"
    working_dir: /opt/kbengine/assets
    environment:
      LOG_LEVEL: INFO
      KBE_COMPONENT_NAME: machine
      KBE_COMPONENT_ID: 1001
      KBE_MACHINE_HOST: localhost
      KBE_MACHINE_PORT: 20099
    ports:
      - 20099:20099
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    healthcheck:
      test: $$ENKI_PYTHON .shedu/enki/cmd/machine/send_onQueryAllInterfaceInfos.py
      interval: 2s
      timeout: 5s
      retries: 1
    entrypoint: bash .shedu/scripts/deploy/start_component.sh

  logger:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      - machine
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-logger
    restart: "no"
    environment:
      LOG_LEVEL: INFO
      KBE_COMPONENT_NAME: logger
      KBE_COMPONENT_ID: 2001
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    entrypoint: bash /opt/kbengine/assets/.shedu/scripts/deploy/start_component.sh

  interfaces:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      - machine
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-interfaces
    restart: "no"
    environment:
      LOG_LEVEL: INFO
      KBE_COMPONENT_NAME: interfaces
      KBE_COMPONENT_ID: 3001
      KBE_INTERFACES_HOST: localhost
      KBE_INTERFACES_PORT: 30099
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    ports:
      - 30099:30099
      # Interfaces telnet
      - 33000:33000
    healthcheck:
      test: $$ENKI_PYTHON .shedu/enki/cmd/interfaces/send_lookApp.py
      interval: 2s
      timeout: 1s
      retries: 1
      start_period: 10s
    entrypoint: bash /opt/kbengine/assets/.shedu/scripts/deploy/start_component.sh

volumes:
  kbe-mariadb-data:
  kbe-log-data:
    external:
      name: ${ELK_COMPOSE_PROJECT_NAME}_kbe-log-data

networks:
  kbe-net:
