version: '3'

x-env:
  &env
  LOG_LEVEL: INFO
  KBE_MACHINE_HOST: ${KBE_COMPONENT_CONTAINER_NAME}-supervisor
  KBE_MACHINE_TCP_PORT: 20099
  GAME_NAME: ${GAME_NAME}
  KBE_CONTAINER_USER: ${KBE_CONTAINER_USER}
  GAME_IDLE_START: ${GAME_IDLE_START}
  UUID: 1000
  KBE_STOP_GRACE_PERIOD: ${KBE_STOP_GRACE_PERIOD}

services:

  mariadb:
    image: ${KBE_DB_IMAGE_TAGGED_NAME}
    container_name: ${KBE_DB_CONTAINER_NAME}
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - kbe-mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - kbe-net
    healthcheck:
      test: >
        mysql ${MYSQL_DATABASE} --host=mariadb -P 3306 --user=${MYSQL_USER}
        --password=${MYSQL_PASSWORD} --silent --execute "SELECT 1;"
      interval: 5s
      timeout: 2s
      retries: 0
    command: --log_warnings=9

  supervisor:
    image: ${KBE_SUPERVISOR_IMAGE_NAME}
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-supervisor
    restart: "no"
    working_dir: /opt/enki
    environment:
      DEBUG_SUPERVISOR: ${DEBUG_SUPERVISOR}
      <<: *env
      GAME_IDLE_START: ""
    ports:
      - 20086:20086/udp
      - 20099:20099/tcp # Порт для запуска приложения под дебагером в контейнере
      - 18198:18198
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/machine/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
    entrypoint: bash start_supervisor.sh

  logger:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      - supervisor
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-logger
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: logger
      KBE_COMPONENT_ID: 2001
      <<: *env
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs/
    networks:
      - kbe-net
    ports:
      # telnet
      - 34000:34000
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
      start_period: 10s
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

  interfaces:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      - supervisor
      - logger
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-interfaces
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: interfaces
      KBE_COMPONENT_ID: 3001
      <<: *env
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    ports:
      - 30099:30099
      # telnet
      - 33000:33000
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      start_period: 10s
      retries: 1
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

  dbmgr:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      mariadb: { condition: service_healthy }
      supervisor: { condition: service_healthy }
      logger: { condition: service_healthy }
      interfaces: { condition: service_healthy }
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-dbmgr
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: dbmgr
      KBE_COMPONENT_ID: 4001
      <<: *env
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    ports:
      # telnet
      - 32000:32000
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
      start_period: 10s
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

  baseappmgr:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      dbmgr: { condition: service_healthy }
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-baseappmgr
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: baseappmgr
      KBE_COMPONENT_ID: 5001
      <<: *env
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
      start_period: 10s
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

  cellappmgr:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      dbmgr: { condition: service_healthy }
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-cellappmgr
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: cellappmgr
      KBE_COMPONENT_ID: 6001
      <<: *env
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
      start_period: 10s
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

  cellapp-7001:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      cellappmgr: { condition: service_healthy }
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-cellapp-1
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: cellapp
      KBE_COMPONENT_ID: 7001
      <<: *env
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    ports:
      # telnet
      - 50001:50000
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
      start_period: 20s
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

  baseapp-8001:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      baseappmgr: { condition: service_healthy }
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-baseapp-1
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: baseapp
      KBE_COMPONENT_ID: 8001
      <<: *env
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    ports:
      # Port for connecting the game client
      - 20015:20015
      - 20005:20005/udp
      # telnet
      - 40001:40000
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
      start_period: 20s
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

  loginapp:
    image: ${KBE_ASSETS_IMAGE_NAME}
    depends_on:
      baseapp-8001: { condition: service_healthy }
      cellapp-7001: { condition: service_healthy }
    container_name: ${KBE_COMPONENT_CONTAINER_NAME}-loginapp
    restart: "no"
    environment:
      KBE_COMPONENT_NAME: loginapp
      KBE_COMPONENT_ID: 9001
      <<: *env
      LOGINAPP_PORT: 20013
    volumes:
      - kbe-log-data:/opt/kbengine/assets/logs
    networks:
      - kbe-net
    ports:
      # Port for connecting the game client
      - 20013:20013
      # telnet
      - 31000:31000
      # Http callback address for email registration
      - 21103:21103
    healthcheck:
      test: >
        test $$GAME_IDLE_START || test $$DISABLE_HEALTHCHECK
        || CACHE_ADDR=1 LOG_LEVEL=ERROR $$ENKI_PYTHON /opt/enki/tools/cmd/common/lookApp.py
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 2s
      retries: 1
      start_period: 20s
    stop_grace_period: ${KBE_STOP_GRACE_PERIOD}
    entrypoint: bash /opt/shedu/scripts/deploy/start_component.sh

volumes:
  kbe-mariadb-data:
    name: ${KBE_DB_VOLUME_NAME}
    external: true
  kbe-log-data:
    name: ${KBE_LOG_VOLUME_NAME}
    external: true

networks:
  kbe-net:
