FROM ubuntu:20.04
LABEL maintainer="Aleksei Burov <burov_alexey@mail.ru>"

#
# Образ библиотеки на Python для сетевого взаимодействия с серверным игровым
# движком KBEngine. Образ содержит библиотеку и собранный Python с
# установленными зависимостями. Так же добавлены инструменты для отладки
# приложения Python, запущенного в контейнере.
#

# Установка зависимостей
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    zlib1g-dev \
    libffi-dev \
    libssl-dev \
    git \
    wget \
    net-tools \
    nano \
    socat \
    netcat \
    tcpdump \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
# Сборка Python 3.13.5
RUN wget https://www.python.org/ftp/python/3.13.5/Python-3.13.5.tgz \
    && tar xvf Python-3.13.5.tgz \
    && cd Python-3.13*/ && ./configure \
        --enable-optimizations \
        --prefix=/opt/python \
    && make -j$(nproc) altinstall \
    && rm -rf /tmp/Python-3.13*
ENV ENKI_PYTHON=/opt/python/bin/python3.13

# Создание пользователя и установка зависимостей Python
ARG KBE_CONTAINER_USER
RUN useradd -m $KBE_CONTAINER_USER
COPY --chown=$KBE_CONTAINER_USER enki /opt/enki
RUN $ENKI_PYTHON -m pip install --upgrade pip \
    && $ENKI_PYTHON -m pip install \
    --no-warn-script-location \
    -r /opt/enki/requirements.txt
ENV PYTHONPATH=/opt/enki
