FROM ubuntu:20.04 AS kbe_pre_build
LABEL maintainer="Aleksei Burov <burov_alexey@mail.ru>"

RUN apt update \
    && apt install -y \
    git

FROM kbe_pre_build AS kbe_compiled
# Download latest sha to be ensure the latest kbe source is up to date.
ADD https://api.github.com/repos/kbengine/kbengine/git/refs/heads/master /tmp/kbe_version.json
RUN git clone https://github.com/kbengine/kbengine.git --progress /opt

ARG COMMIT_SHA
WORKDIR /opt
RUN git checkout ${COMMIT_SHA} -b kbe-deploy-branch-${COMMIT_SHA}

WORKDIR /opt/kbe/src/

# Для установки GCC 5
RUN echo "deb http://dk.archive.ubuntu.com/ubuntu xenial main" >> /etc/apt/sources.list \
    && echo "deb http://dk.archive.ubuntu.com/ubuntu xenial universe" >> /etc/apt/sources.list
RUN apt install gnupg2 -y
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32
RUN cd /etc/apt \
    && cp trusted.gpg trusted.gpg.d

RUN apt update
RUN apt install gcc g++ g++-5 gcc-5 make git autoconf libtool \
    libmysqlclient-dev -y

ENV CC=gcc-5
ENV CXX=g++-5
RUN make

FROM kbe_pre_build
# Copy only the compiled binary files and the resources
COPY --from=kbe_compiled /opt/kbe/bin/ /opt/kbengine/kbe/bin/
COPY --from=kbe_compiled /opt/kbe/res/ /opt/kbengine/kbe/res/
