FROM centos:centos7
LABEL maintainer="Aleksei Burov <burov_alexey@mail.ru>"

WORKDIR /tmp
RUN yum groupinstall "Development Tools" -y
RUN yum install -y epel-release
RUN yum install openssl-devel -y
RUN yum install wget zlib-devel -y

RUN wget https://www.python.org/ftp/python/3.9.16/Python-3.9.16.tgz
RUN tar xvf Python-3.9.16.tgz

RUN cd Python-3.9*/ && ./configure \
    --enable-optimizations \
    --prefix=/opt/python
RUN cd Python-3.9*/ && make altinstall
