ARG FROM_IMAGE_NAME
FROM ${FROM_IMAGE_NAME}
LABEL maintainer="Aleksei Burov <burov_alexey@mail.ru>"

# We assume the context is the assets directory
COPY . /opt/assets

# Modify kbengine.xml file KBEngine works with the docker environment
ARG HOST_ADDR
RUN HOST_ADDR=${HOST_ADDR} python3 /opt/assets/modify_kbe_config.py

WORKDIR /opt/assets/

ENTRYPOINT bash /opt/assets/docker-entrypoint.sh
